//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspMVC.Test {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspMVC.Test.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;id&quot;:2,&quot;name&quot;:&quot;Andrey&quot;,&quot;surname&quot;:&quot;Kopilov&quot;,&quot;age&quot;:28,&quot;email&quot;:&quot;E-mail2&quot;,&quot;registationDate&quot;:&quot;2022-10-12T00:00:00&quot;}].
        /// </summary>
        internal static string ExpectedFindContent {
            get {
                return ResourceManager.GetString("ExpectedFindContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;id&quot;:2,&quot;name&quot;:&quot;Andrey&quot;,&quot;surname&quot;:&quot;Kopilov&quot;,&quot;age&quot;:28,&quot;email&quot;:&quot;E-mail2&quot;,&quot;registationDate&quot;:&quot;2022-10-12T00:00:00&quot;}.
        /// </summary>
        internal static string UpdateContent {
            get {
                return ResourceManager.GetString("UpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;id&quot;:2,&quot;name&quot;:&quot;Andrey&quot;,&quot;surname&quot;:&quot;Kopilov&quot;,&quot;age&quot;:29,&quot;email&quot;:&quot;E-mail2&quot;,&quot;registationDate&quot;:&quot;2022-10-12T00:00:00&quot;},{&quot;id&quot;:3,&quot;name&quot;:&quot;Konstantin&quot;,&quot;surname&quot;:&quot;Lapin&quot;,&quot;age&quot;:37,&quot;email&quot;:&quot;E-mail3&quot;,&quot;registationDate&quot;:&quot;2022-10-12T00:00:00&quot;},{&quot;id&quot;:5,&quot;name&quot;:&quot;Katya&quot;,&quot;surname&quot;:&quot;Barinova&quot;,&quot;age&quot;:26,&quot;email&quot;:&quot;Email-5&quot;,&quot;registationDate&quot;:&quot;2022-10-13T00:00:00&quot;},{&quot;id&quot;:6,&quot;name&quot;:&quot;Ivan&quot;,&quot;surname&quot;:&quot;Ivanov&quot;,&quot;age&quot;:24,&quot;email&quot;:&quot;E-mail24&quot;,&quot;registationDate&quot;:&quot;2022-10-13T00:00:00&quot;}].
        /// </summary>
        internal static string UserServiceGetAllResult {
            get {
                return ResourceManager.GetString("UserServiceGetAllResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;id&quot;:2,&quot;name&quot;:&quot;Andrey&quot;,&quot;surname&quot;:&quot;Kopilov&quot;,&quot;age&quot;:28,&quot;email&quot;:&quot;E-mail2&quot;,&quot;registationDate&quot;:&quot;2022-10-12T00:00:00&quot;}.
        /// </summary>
        internal static string UserServiceGetItemResult {
            get {
                return ResourceManager.GetString("UserServiceGetItemResult", resourceCulture);
            }
        }
    }
}
